version: '3'
services:
  mongo:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  api-gateway:
    build: ./api-gateway
    ports:
      - "80:80"
    depends_on:
      - user-service
      - restaurant-service
      - order-service

  user-service:
    build: ./user-service
    ports:
      - "5000:5000"
    depends_on:
      - mongo

  restaurant-service:
    build: ./restaurant-service
    ports:
      - "5001:5001"
    depends_on:
      - mongo

  order-service:
    build: ./order-service
    ports:
      - "5002:5002"
    depends_on:
      - mongo

volumes:
  mongo-data:
